### PR TITLE
Adding NetLogo model

### PR DESCRIPTION
**Pull request by smile4life**
Hopefully this adds a "spread" folder to the modelling folder, with the network NetLogo model inside it

### CODE REVIEW

**Comment by jrhawley** [comment]
Yeah, this PR will do that once we merge it. I've never seen NetLogo before, what's this script trying to do?

**Comment by smile4life** [comment]
This script (after I finish with it) should model the spread of a virus through a leaf (network of cells connected by plasmodesmata). NetLogo is an agent-based modelling program that has its own "NetLogo" language - apparently pretty popular with iGEM teams

**Comment by alexanian** [comment]
Ehh, I am just going to merge this so it's easy for other people to work with. I am confused by all the

```
                _,.---.---.---.--.._ 
            _.-' `--.`---.`---'-. _,`--.._
           /`--._ .'.     `.     `,`-.`-._\
          ||   \  `.`---.__`__..-`. ,'`-._/
     _  ,`\ `-._\   \    `.    `_.-`-._,``-.
  ,`   `-_ \/ `-.`--.\    _\_.-'\__.-`-.`-._`.
 (_.o> ,--. `._/'--.-`,--`  \_.-'       \`-._ \
  `---'    `._ `---._/__,----`           `-. `-\
            /_, ,  _..-'                    `-._\
            \_, \/ ._(
             \_, \/ ._\
              `._,\/ ._\
                `._// ./`-._
         LGB      `-._-_-_.-'
```

but oh well, I think NetLogo is just not meant to be parsed by eyes.

**Comment by alexanian** [comment]
In your next commit, could you include a header and an indicating via commenting of the point in the file where we know longer have to pay attention, because it's all NetLogo GUI instructions?

**Pull request merged**
