### PR TITLE
SAR Signalling & Apoptosis

### PR DESCRIPTION
**Pull request by smile4life**
Created a variable to measure the amount of SAR molecule being produced. The user can specify a level of molecule required for apoptosis to occur. 
The amount spreading to other cells, the apoptosis requirement level, and the way sar molecules are first generated are unsupported, but at least the framework's there?

### CODE REVIEW

**Comment by smile4life** [comment]
Don't know how I missed adding that chunk of John's work to my fork, but it should be good now :)

**Comment by mattsmart** [comment]
This code is really long and quickly going over my head lol. @JeffGoldblum (John) can you comment?

**Comment by smile4life** [comment]
Would it be helpful for me to just put the contents of the "Code" tab here?

```
;; ----- DECLARATIONS -----
;; Create "breed" of 'turtle' called cell
breed [cells cell]          ;; eventually separate mesophyll?
breed [vasculars vascular]  ;; phloem vascular bundles 

;; Create "breed" of 'link' called phloem
directed-link-breed [phloems phloem]  
;; Note: I know there shouldn't be an s, but it wanted a different plural :(
undirected-link-breed [plasmodesmata plasmodesma]

;; Declare global variables
globals
[
  num-infected   ;; keep track of number infected
  num-viruses    ;; keep track of the viral particles
  mod-num-viruses  ;; keep track of the modified viral particles
  lysed-cells    ;; keep track of apoptotic cells
]

;; Declare the cell-specific (turtle breed) variables
cells-own
[
  infected?         ;; if true, the cell is infectious
  resistant?        ;; if true, cell can't be infected
  num-plasmodesmata ;; number of connections with other cells
  copy-number       ;; track the number of genomes in the nucleus
  pregenomes        ;; track the number of pregenomes in the cell
  protein-six       ;; track functional P6
  viral-count       ;; keeps track of the virions produced by the cell
  mod-copy-number   ;; as above with delta-P6
  mod-pregenomes    ;; as above with delta-P6
  mod-viral-count   ;; as above with delta-P6
  sar-level         ;; amount of "salicylic acid" present in the cell
]





;; Setup procedures
to setup
  clear-all    ;; remove anything from previous runs
  setup-stem   ;; make a stem structure to connect the leaves
  setup-cells  ;; set up the cells
  setup-leaf   ;; set up the connections between cells
  ask n-of initial-infection-sites cells   ;; infect this number of cells
    [ 
      become-infected 
      set copy-number founder-population-viruses ;; start with x genomes per infected cell
    ]
  ask links [ set color white ]  ;; make the symplastic connections white
  ask phloems 
    [ 
      set color green            ;; make the vascular bundles green and thicker
      set thickness 0.3
    ]
  reset-ticks  ;; reset timer from previous run
end

to setup-stem
  set-default-shape vasculars "plant" ;; uses stem-looking shape for vasculature
  ;; Create and position vascular cells
  create-vasculars 1 [ setxy 0 -16 ]
  create-vasculars 1 
  [ 
    setxy 0 -6 
    create-phloem-from vascular 0 ;; directed stem connection
  ]
  create-vasculars 1 
  [ 
    setxy 0 6 
    create-phloem-from vascular 1 ;; directed stem connection
  ]
  create-vasculars 1 
  [ 
    setxy 0 16 
    create-phloem-from vascular 2 ;; directed stem connection
  ]
  ask vasculars         ;; make the vasculature stand out from the leaf cells
    [ 
      set color green 
      set size 2.5
    ]
end

to setup-cells
  set-default-shape cells "circle"   ;; uses circle shape for displayed cells
  create-cells num-cells
  [
    let xguess random-pxcor
    while [abs xguess < 0.1 * max-pxcor or abs xguess > 0.95 * max-pxcor]
      [set xguess random-pxcor]

     let yguess random-pycor
    while [abs yguess < 0.1 * max-pycor or abs yguess > 0.95 * max-pycor]
      [set yguess random-pycor] 

    setxy xguess yguess ;; no nodes too close to edges
    become-susceptible
    ask cells [ set size 0.5 ]       ;; makes the circles smaller for larger scale
  ]
end

to setup-leaf
  ask cells 
  [ 
    ;; using random-possion to give a more realistic distribution of links per cell
    while [ count my-links < random-poisson avg-num-plasmodesmata ]
    [ 
      let choice (min-one-of (other cells with [not link-neighbor? myself])
                              [distance myself])
      if choice != nobody [ create-plasmodesma-with choice ]
    ]
  ]
  ;; to make the network look nicer
  repeat 10 [ layout-spring turtles links 0.3 (world-width / (sqrt num-cells)) 1 ]
  ;; connect leaves to the vasculature
  ask vascular 0 
  [ 
    let choice ( one-of (cells with [pxcor < 0 and pycor < 0]) )
    if choice != nobody [ create-phloem-from choice ]
  ]
  ask vascular 1 
  [ 
    let choice ( one-of (cells with [pxcor > 0 and pycor < 0]) )
    if choice != nobody [ create-phloem-from choice ]
  ]
  ask vascular 2 
  [ 
    let choice ( one-of (cells with [pxcor < 0 and pycor > 0]) )
    if choice != nobody [ create-phloem-from choice ]
  ]
  ask vascular 3
  [ 
    let choice ( one-of (cells with [pxcor > 0 and pycor > 0]) )
    if choice != nobody [ create-phloem-from choice ]
  ]
end




;; ----- MAIN -----

;; This is the main process - what is activated when the user clicks "go"
to go
  ;; if the user specified a duration, stop after that
  if specified-duration
  [
    if ticks > num-ticks [ stop ] 
  ]
  ;; otherwise, check if all cells are infected
  if all? cells [ infected? ] 
  [  
    ;; if they are, run 40 more times (make the graph look nice)
    let i 0 
    while [i <= 40] 
    [
      spread-virus
      set i i + 1
      tick
    ]
    stop  ;; stop model completely
  ]

  ;; otherwise, continue to spread the virus
  spread-virus
  spread-sar
  do-apoptosis-checks
  tick
end




;;  ----- CELL PROCEDURES -----

;; Cell Procedures
to become-infected
  set infected? true
  set resistant? false
  set color red
  ;; determine number of viruses entering the susceptible cell
  ;let new-viruses ( sum [viral-count] of link-neighbors )
  ;set viral-count 0 ; new-viruses
  set copy-number copy-number + 1
  set num-viruses num-viruses + 1
end

to mod-become-infected
  set infected? true
  set resistant? false
  set color red
  set mod-copy-number copy-number + 1
  set mod-num-viruses mod-num-viruses + 1
end

to become-susceptible
  set infected? false
  set resistant? false
  set color green
  set copy-number 0
  set pregenomes 0
  set protein-six 0
  set viral-count 0
  set mod-copy-number 0
  set mod-pregenomes 0
  set mod-viral-count 0
end


;; ---- SAR Molecule Spread & Apoptosis ----

;; Increase levels of signalling molecule based on neighbours' levels
;; Assuming the infected cells are unable to produce sar signal molecules, but 
to spread-sar
  ;; initial generation of sar based on neighbouring cells being infected
  ask cells
  [
    let neighboured false           ;; remember if a neighbour is infected
    ask link-neighbors 
    [
      if (infected?) [ set neighboured true ]
    ]
    ;; if a neighbour is infected, increase this cell's sar signalling molecule
    if (neighboured) [ set sar-level sar-level + 1 ]
  ]
  ;; assume the resistant cells are better able to spread the sar molecule
  ask cells with [resistant?]
  [
    let shared-sar sar-level / 2     ;; saying half the sar-level will be spread
    ask link-neighbors 
    [ 
      set sar-level sar-level + shared-sar 
      if sar-level >= resistance-threshold [ set resistant? true ]
    ]
    set sar-level sar-level + shared-sar / 2  ;; not much kept in the cell
  ]
  ;; assume the susceptible cells can produce an okay amount of sar molecule
  ask cells with [not infected? and not resistant?]
  [
    let shared-sar sar-level / 5     ;; fifth of the molecules will be shared
    ask link-neighbors
    [
      set sar-level sar-level + shared-sar
      if sar-level >= resistance-threshold [ set resistant? true ]
    ]
    set sar-level sar-level + shared-sar / 2
  ]
end  

;; Determine whether the cell can destroy itself to help prevent viral spread
to do-apoptosis-checks
  ;; if the cell is infected and can still lyse, check 
  ask cells with [infected?] 
  [
    if (sar-level >= lysis-threshold)
      [ 
        set color violet
        die 
        set lysed-cells lysed-cells + 1
      ] 
  ]
end



;;  ----- VIRUS PROCEDURES -----

;; Procedure governing spread to neighbouring cells
to spread-virus
  ask cells with [infected?]
    [ 
      if (viral-count + mod-viral-count > 500)
        [
          ask link-neighbors with [not resistant? and not infected?]
            [ 
              if (random-float 100 < viral-spread-chance)
                [ 
                  become-infected                   ;; If chance has it, infect the cell
                  set num-infected num-infected + 1 ;; increase the count for infected cells
                ] 
            ] 
        ]
    ]
end

to assemble-virus
  ask cells with [infected?]
    [
      ;; 35S RNA formation
      if (viral-count + mod-viral-count < 500)
        [
          set pregenomes pregenomes + 0.01 * copy-number
          ;set mod-viral-count mod-viral-count + mod-copy-number
        ]
      ;; P6 production
      if (protein-six < 1000)
        [
          set protein-six protein-six + 0.01 * copy-number
        ]
      ;; Viral assembly
      if (viral-count + mod-viral-count < 500)
        [
          set viral-count viral-count + 0.01 * protein-six * pregenomes
          ;set mod-viral-count mod-viral-count + mod-copy-number
        ]
      ;; Reentry in nucleus
      if (copy-number + mod-copy-number < 100)
        [
          set copy-number copy-number + 0.01 * viral-count
          ;set mod-copy-number 1.05 * mod-copy-number
        ]

    ]
end
```

**Comment by JeffGoldblum** [comment]
It looks good to commit

Edit: It's ok to commit for now, but the addition of SAR instantly kills the infected cells and stops the infection. I don't think that's realistic and will need to be fixed in the future.

**Comment by jrhawley** [comment]
K, sounds good. Merging

**Pull request merged**
