### PR TITLE
Added multiprocessing

### PR DESCRIPTION
**Pull request by Ellmen**
I think this should work but someone should definitely review/test it. I wrapped the main for loop in a function which takes in a start and end for the permutation #s it should be computing. That way the loop at the end can automatically distribute the work evenly among the threads.

### CODE REVIEW

**Comment by mattsmart** [comment]
I'm against merging this until we can verify that it saves RAM relative to calling the script multiple times (on either OS).

Right now I can call the original script twice (split the jobs into 2), cutting my total runtime in half, for 6GB of RAM. Using this PRs version, it takes just as long (bc 2 threads) but 9GB of RAM for the overhead of initializing rosetta in the same script. 

Unless we can find a way to get < 3GB RAM per thread, we may be better off with the original. Thoughts?

**Comment by jrhawley** [comment]
Yeah, that's probably a good idea ^ for now. Just running multiple instances seems more stable atm, too. We can work on it though. I know you wanted to make a few more changes, Isaac

**Comment by mattsmart** [comment]
Closing bc switch to argparse/batch scripts instead of explicit multithreading

**Comment by mattsmart** [comment]
nvm

**Pull request closed without merging**
