### PR TITLE
Plot camv genome

### PR DESCRIPTION
**Pull request by mattsmart**
Plots genome as a disk

TODO: 
- include targets in plot (location + identifier?), sense isn't accounted for / location inaccurate
- include targets status in plot (cut/not)

Questions:
- should a gene be 'broken' if it contains an open target

### CODE REVIEW

**Comment by mattsmart** [comment]
sample output
figure_1

**Comment by alexanian** [comment]
Exciting! The grey looks good, pretty subtle. Can you increase the font size of the central text and put the time in the center as well?

**Comment by Ellmen** [comment]
Looks nice! Should we be concerned that it's initializing with only 3/4 active targets?

**Comment by mattsmart** [comment]
Yes! It's arbitrary lol, I need to implement target annotation

**Comment by Ellmen** [comment]
Ah okay I thought it was initializing the genome improperly

**Comment by mattsmart** [comment]
Updated colours, red means broken gene, lmk what you guys think about the colours
figure_1

**Comment by Ellmen** [comment]
I like it

**Comment by mattsmart** [comment]
to annotate active vs inactive targets, what symbols should  i use? I need symbols for 3 states:
- repaired (and targetable)
- open/cut (not currently targetable)
- inactivated (no longer targetable)

**Comment by mattsmart** [comment]
here's what it looks like for open targets
figure_1

**Comment by mattsmart** [comment]
and here for repaired targets
test_genome

**Comment by Ellmen** [comment]
LGTM

**Comment by mattsmart** [comment]
LGTIsaac

**Pull request merged**
